student_sys/student_sys/student_sys/urls.py
from django.contrib import admin
from django.conf.urls import url

from student.views import index,stuadd
urlpatterns = [
    url(r'^$', index,name="index"),
    url(r'^stuadd',stuadd,name="stuadd"),
    url(r'^admin/', admin.site.urls),
]

student_sys/student_sys/student/models.py
from django.db import models


class Student(models.Model):
    SEX_ITEMS = [
        (1,'男'),
        (2,'女'),
        (0,'未知'),        
    ]
    
    STATUS_ITEMS=[
        (0,'申请'),
        (1,'通过'),
        (2,'拒绝'),        
    ]
    
    
    name = models.CharField(max_length=128,verbose_name="姓名")
    sex = models.IntegerField(choices=SEX_ITEMS, verbose_name="性别")
    profession = models.CharField(max_length=128,verbose_name="职业")
    email = models.EmailField(verbose_name="Email")
    qq = models.CharField(max_length=128,verbose_name="QQ")
    phone = models.CharField(max_length=128,verbose_name="电话")
    status = models.IntegerField(choices=STATUS_ITEMS,default=0,verbose_name="审核状态")
    created_time = models.DateTimeField(auto_now_add=True,editable=False,verbose_name="创建时间")
    
    def __str__(self):
        return '<Student:{}>'.format(self.name)
    
    class Meat:
        verbose_name = verbose_name_plural = "学员信息"

student_sys/student_sys/student/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Student


class StudentForm(forms.ModelForm):
    def clean_qq(self):
            cleaned_data = self.cleaned_data['qq']
            if not cleaned_data.isdigit():
                return forms.ValidationError('必须时数字')
            return int(cleaned_data)
        
    class Meta:
            model = Student
            fields  = ( 'name','sex','profession','status','email','qq','phone')

    

student_sys/student_sys/student/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Student

from django.urls import reverse
from .forms import StudentForm



def index(request):
    allstu = Student.objects.all()

    context = {
        "stulist": allstu,

    }

    return render(request, 'index.html', context=context)

def stuadd(request):

    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        form = StudentForm()

    context = {

        "form": form,
    }

    return render(request, 'stuadd.html', context=context)

student_sys/student_sys/student/templates/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title></title>
		<link rel="stylesheet" href="../static/css/mycss.css">
		
	</head>
	<body>
		{% for stu in stulist  %}
		
		 <li>{{ stu.name }} - {{ stu.get_status_display }} {{stu.get_sex_display}} {{ stu.profession }} </li>
		
		{% endfor %}

        <a href="/stuadd">新增学生</a>
	</body>
</html>

student_sys/student_sys/student/templates/stuadd.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>学生的新增</title>
		<link rel="stylesheet" href="../static/css/mycss.css">

	</head>
	<body>

		<form action="/stuadd" method="post">
           {% csrf_token %}
           <table>
               <tr><td>姓名</td><td>{{ form.name }}</td></tr>
               <tr><td>性别</td><td>{{ form.sex }}</td></tr>
               <tr><td>职业</td><td>{{ form.profession }}</td></tr>
               <tr><td>审核状态</td><td>{{ form.status }}</td></tr>
               <tr><td>邮箱</td><td>{{ form.email }}</td></tr>
               <tr><td>qq</td><td>{{ form.qq }}</td></tr>
               <tr><td>电话</td><td>{{ form.phone }}</td></tr>
           </table>
           <input type="submit" value="添加" />
       </form>

	</body>
</html>